<template>
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top glass-nav">
    <div class="container">
      <router-link class="navbar-brand fw-bold" :to="{ name: 'home' }">
        <img class="navbar-brand-logo rotate-in-center" src="@/assets/imgs/universe.png" alt="">CineVerse</router-link>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="d-flex flex-grow-1 mx-lg-5 my-2 my-lg-0" role="search">
          <input class="form-control me-2 search-bar" type="search" placeholder="Tìm kiếm phim, series, anime..."
            aria-label="Search">
        </form>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
          <li class="nav-item"><a class="nav-link" href="#">Phim Điện Ảnh</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Phim Truyền Hình</a></li>
          <li class="nav-item">
            <RouterLink :to="{ name: 'user.watchlist' }" class="nav-link" href="#">Watchlists</RouterLink>
          </li>
          <li class="nav-item"><a class="nav-link" href="#">Cộng đồng</a></li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                class="bi bi-person-circle" viewBox="0 0 16 16">
                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                <path fill-rule="evenodd"
                  d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
              </svg>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { RouterLink } from 'vue-router';
</script>

<style>
/* --- Thanh điều hướng --- */
.glass-nav {
  background: var(--surface-glass);
  backdrop-filter: blur(15px);
  -webkit-backdrop-filter: blur(15px);
  border-bottom: 1px solid var(--border-glass);
}

.navbar-brand .navbar-brand-logo {
  width: 40px;
  height: 40px;
  margin-right: 10px;
}

.navbar-brand:hover {
  color: var(--starlight-yellow);
}

/* Animation */
.rotate-in-center {
  animation: rotate-in-center 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-7-12 10:44:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-in-center
 * ----------------------------------------
 */
@keyframes rotate-in-center {
  0% {
    transform: rotate(-360deg);
    opacity: 0;
  }

  100% {
    transform: rotate(0);
    opacity: 1;
  }
}

.nav-link:hover,
.nav-link:focus {
  color: var(--starlight-yellow);
  font-weight: 700;
}

.search-bar {
  background-color: rgba(0, 0, 0, 0.2);
  border: 1px solid var(--border-glass);
  color: var(--nebula-white);
}

.search-bar::placeholder {
  color: rgba(255, 255, 255, 0.6);
}

.search-bar:focus {
  background-color: rgba(0, 0, 0, 0.4);
  border-color: var(--starlight-yellow);
  box-shadow: 0 0 0 0.25rem rgba(255, 217, 77, 0.25);
  color: var(--nebula-white);
}
</style>