<template>
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top glass-nav">
    <div class="container">
      <router-link class="navbar-brand fw-bold" :to="{ name: 'home' }">
        <img class="navbar-brand-logo rotate-in-center" src="@/assets/imgs/universe.png" alt="">CineVerse</router-link>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="d-flex flex-grow-1 mx-lg-5 my-2 my-lg-0" role="search">
          <input class="form-control me-2 search-bar" type="search" placeholder="Tìm kiếm phim, series, anime..."
            aria-label="Search">
        </form>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-center">
          <li class="nav-item">
            <div class="btn-group">
              <button type="button" class="btn action nav-link">Movies</button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Anime</a></li>
                <li><a class="dropdown-item" href="#">TV-Series</a></li>
                <li><a class="dropdown-item" href="#">Trailers</a></li>
                <li><a class="dropdown-item" href="#">Top 10</a></li>
                <li><a class="dropdown-item" href="#">Genres</a></li>
                <li><a class="dropdown-item" href="#">Latest</a></li>
                <li><a class="dropdown-item" href="#">Upcoming</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <router-link :to="{ name: 'user.watchlist' }" class="nav-link" href="#">Watchlists</router-link>
          </li>
          <li class="nav-item">
            <div class="btn-group">
              <button type="button" class="btn action nav-link">Community</button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Clubs</a></li>
                <li><a class="dropdown-item" href="#">Users</a></li>
                <li><a class="dropdown-item" href="#">Blogs</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <div class="btn-group">
              <button type="button" class="btn action nav-link">Help</button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">About</a></li>
                <li><a class="dropdown-item" href="#">Support</a></li>
                <li><a class="dropdown-item" href="#">Advertising</a></li>
                <li><a class="dropdown-item" href="#">FAQ</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <div class="btn-group profile">
              <button type="button" class="btn action nav-link "><i class="fa-solid fa-circle-user fs-4 text"></i>
              </button>
              <ul v-if="isAuthenticated" class="dropdown-menu ">
                <li><router-link :to="{ name: 'user.watchlist' }" class="dropdown-item">Watchlist</router-link></li>
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><a class="dropdown-item" href="#">Setting</a></li>
                <li><a class="dropdown-item" @click="handleLogout">Logout</a></li>
              </ul>
              <ul v-else class="dropdown-menu">
                <li><router-link to="/auth" class="dropdown-item">Login </router-link></li>
                <li><router-link to="/auth" class="dropdown-item">Register</router-link></li>
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { RouterLink, useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import { computed } from 'vue';


const authStore = useAuthStore();
const isAuthenticated = computed(() => authStore.isAuthenticated);
const router = useRouter();

function handleLogout() {
  if (confirm("Bạn có chắn muốn đăng xuất?")) {
    authStore.logout()
    router.push('/')
  }
}
</script>

<style>
/* --- Thanh điều hướng --- */
.glass-nav {
  background: var(--surface-glass);
  backdrop-filter: blur(15px);
  -webkit-backdrop-filter: blur(15px);
  border-bottom: 1px solid var(--border-glass);
}

.navbar-brand .navbar-brand-logo {
  width: 40px;
  height: 40px;
  margin-right: 10px;
}

.navbar-brand:hover {
  color: var(--starlight-yellow);
}

/* Animation */
.rotate-in-center:hover {
  animation: rotate-in-center 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2025-7-12 10:44:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-in-center
 * ----------------------------------------
 */
@keyframes rotate-in-center {
  0% {
    transform: rotate(-360deg);
    opacity: 0;
  }

  100% {
    transform: rotate(0);
    opacity: 1;
  }
}

.nav-link:hover,
.nav-link:focus {
  color: var(--starlight-yellow);
  font-weight: 700;
  background-color: var(--surface-glass);
}

.btn-group .dropdown-menu {
  background-color: var(--deep-space-black);
  border: 1px solid var(--border-glass);
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
}

.btn-group:hover .dropdown-menu {
  display: block;
  margin-top: 30px;
}

.btn-group .dropdown-menu .dropdown-item {
  color: var(--nebula-white);
  padding: 10px 20px;
  text-decoration: none;
}

.btn-group .dropdown-menu .dropdown-item:hover {
  background-color: var(--galaxy-purple);
  font-weight: 700;
  color: var(--nebula-white);
}

/* .profile .dropdown-menu {
  right: -80px;
  width: max-content;
  text-align: center;

} */

.search-bar {
  background-color: rgba(0, 0, 0, 0.2);
  border: 1px solid var(--border-glass);
  color: var(--nebula-white);
}

.search-bar::placeholder {
  color: rgba(255, 255, 255, 0.6);
}

.search-bar:focus {
  background-color: rgba(0, 0, 0, 0.4);
  border-color: var(--galaxy-purple);
  box-shadow: 0 0 0 0.25rem rgba(145, 49, 255, 0.25);
  color: var(--nebula-white);
}
</style>